-- MySQL Script generated by MySQL Workbench
-- Tue 19 Jan 2016 06:27:11 PM EET
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema chat_demo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `chat_demo` ;
CREATE SCHEMA IF NOT EXISTS `chat_demo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `chat_demo` ;

-- -----------------------------------------------------
-- Table `chat_demo`.`chat_rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat_demo`.`chat_rooms` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `user_A` VARCHAR(45) NOT NULL,
  `user_B` VARCHAR(45) NOT NULL,
  `startTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat_demo`.`chat_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat_demo`.`chat_messages` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_from` VARCHAR(45) NOT NULL,
  `message` VARCHAR(1024) NOT NULL,
  `time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `chat_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chat_messages_chat_idx` (`chat_id` ASC),
  CONSTRAINT `fk_chat_messages_chat`
    FOREIGN KEY (`chat_id`)
    REFERENCES `chat_demo`.`chat_rooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
